[package]
name = "juniper_iron"
version = "0.1.1"
authors = [
    "Magnus Hallin <mhallin@fastmail.com>",
    "Christoph Herzog <chris@theduke.at>",
]
description = "Iron integration for juniper"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper_iron"
repository = "https://github.com/graphql-rust/juniper"

[dependencies]
serde = { version = "1.0.2" }
serde_json = { version = "1.0.2" }
juniper = { version = "0.9.2", path = "../juniper" }

urlencoded = { version = "0.5.0" }
iron = "0.5.1"

[dev-dependencies]
iron-test = "^0.5.0"
router = "^0.5.0"
mount = "^0.3.0"
logger = "^0.3.0"

[dev-dependencies.juniper]
version = "0.9.2"
features = ["expose-test-schema", "serde_json"]
path = "../juniper"
