[workspace]
# Order is important as this is the order the crates will be released.
members = [
  "juniper_benchmarks",
  "juniper_codegen",
  "juniper",
  "integration_tests/juniper_tests",
  "integration_tests/async_await",
  "juniper_hyper",
  "juniper_iron",
  "juniper_rocket",
  "juniper_rocket_async",
  "juniper_subscriptions",
  "juniper_warp",
  "juniper_actix",
]
exclude = [
  "docs/book/tests",
  "examples/warp_async",
  "examples/warp_subscriptions",
]
