[workspace]
members = [
    "benches",
    "examples/basic_subscriptions",
    "examples/warp_async",
    "examples/warp_subscriptions",
    "examples/actix_subscriptions",
    "juniper_codegen",
    "juniper",
    "juniper_hyper",
    "juniper_iron",
    "juniper_rocket",
    "juniper_subscriptions",
    "juniper_graphql_ws",
    "juniper_warp",
    "juniper_actix",
    "tests/codegen",
    "tests/integration",
]
