[package]
name = "juniper"
version = "0.7.0"
authors = ["Magnus Hallin <mhallin@fastmail.com>"]
description = "GraphQL server library"
license = "BSD-2-Clause"
documentation = "http://mhallin.github.io/juniper"
repository = "https://github.com/mhallin/juniper"
readme = "README.md"
keywords = ["graphql", "server", "iron", "http", "web"]
categories = ["web-programming"]

[[bench]]
name = "bench"
harness = false
path = "benches/bench.rs"

[features]
default = ["serde", "serde_json"]
nightly = []
iron-handlers = ["iron", "default", "serde_derive", "urlencoded"]
expose-test-schema = []

[dependencies]
iron = { version = "^0.5.1", optional = true }
serde = { version = "^0.9.1", optional = true }
serde_json = {version ="^0.9.1", optional = true }
serde_derive = {version="^0.9.1", optional = true }
urlencoded = {version="0.5", optional=true}


[dev-dependencies]
iron = "^0.5.1"
router = "^0.5.0"
mount = "^0.3.0"
logger = "^0.3.0"
iron-test = "^0.5.0"
bencher = "^0.1.2"
