[package]
name = "juniper_tests"
version = "0.1.0"
publish = false
edition = "2018"

[features]
async = ["juniper/async", "futures"]

[dependencies]
juniper = { path = "../../juniper" }
futures = { version = "=0.3.1", optional = true }

[dev-dependencies]
serde_json = { version = "1" }
fnv = "1.0.3"