[package]
name = "juniper_tests"
version = "0.1.0"
publish = false
edition = "2018"

[dependencies]
juniper = { path = "../../juniper" }
futures = "0.3.1"

[dev-dependencies]
serde_json = { version = "1" }
fnv = "1.0.3"
tokio = { version = "0.2", features = ["rt-core", "time", "macros"] }