# Testing for juniper_hyper is disabled due to a bug in rustc # which causes 
# an internal compiler error.
# TODO: remove this file completely once the crate compiles again.

[tasks.build-verbose]
condition = { channels = ["nightly"] }

[tasks.test-verbose]
condition = { channels = ["nightly"] }

[tasks.ci-coverage-flow]
condition = { channels = ["nightly"] }
