
[env]
CARGO_MAKE_CARGO_ALL_FEATURES = ""

[tasks.build-verbose]
condition = { rust_version = { min = "1.29.0" } }

[tasks.build-verbose.windows]
condition = { rust_version = { min = "1.29.0" }, env = { "TARGET" = "x86_64-pc-windows-msvc" } }

[tasks.test-verbose]
condition = { rust_version = { min = "1.29.0" } }

[tasks.test-verbose.windows]
condition = { rust_version = { min = "1.29.0" }, env = { "TARGET" = "x86_64-pc-windows-msvc" } }

[tasks.ci-coverage-flow]
condition = { rust_version = { min = "1.29.0" } }

[tasks.ci-coverage-flow.windows]
disabled = true
