[package]
name = "juniper_warp"
version = "0.2.0"
authors = ["Tom HoulÃ© <tom@tomhoule.com>"]
description = "Juniper GraphQL integration with Warp"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper_warp"
repository = "https://github.com/graphql-rust/juniper"

[dependencies]
warp = "0.1.8"
juniper = { path = "../juniper", version = ">=0.9, 0.10.0", default-features = false  }
serde_json = "1.0.24"
serde_derive = "1.0.75"
failure = "0.1.2"
futures = "0.1.23"
serde = "1.0.75"
tokio-threadpool = "0.1.7"

[dev-dependencies]
juniper = { path = "../juniper", version = "0.10.0", features = ["expose-test-schema", "serde_json"] }
percent-encoding = "1.0"
