[package]
name = "juniper_warp"
version = "0.5.2"
authors = ["Tom Houl√© <tom@tomhoule.com>"]
description = "Juniper GraphQL integration with Warp"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper_warp"
repository = "https://github.com/graphql-rust/juniper"
edition = "2018"

[features]
subscriptions = ["juniper_subscriptions"]

[dependencies]
warp = "0.2"
futures = { version = "0.3.1", features = ["compat"] }
juniper = { version = "0.14.2", path = "../juniper", default-features = false  }
juniper_subscriptions = { path = "../juniper_subscriptions", optional = true}
tokio = { version = "0.2", features = ["rt-core", "blocking"] }
serde_json = "1.0.24"
serde_derive = "1.0.75"
failure = "0.1.7"
serde = "1.0.75"

[dev-dependencies]
juniper = { version = "0.14.2", path = "../juniper", features = ["expose-test-schema", "serde_json"] }
env_logger = "0.5.11"
log = "0.4.3"
percent-encoding = "1.0"
tokio = { version = "0.2", features = ["rt-core", "macros", "blocking"] }
