[package]
name = "juniper_warp"
version = "0.4.1"
authors = ["Tom Houl√© <tom@tomhoule.com>"]
description = "Juniper GraphQL integration with Warp"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper_warp"
repository = "https://github.com/graphql-rust/juniper"
edition = "2018"

[features]
async = [ "juniper/async", "futures03" ]

[dependencies]
warp = "0.1.8"
juniper = { version = "0.13.1", path = "../juniper" }
serde_json = "1.0.24"
serde_derive = "1.0.75"
failure = "0.1.2"
futures = "0.1.23"
serde = "1.0.75"
tokio-threadpool = "0.1.7"

futures03 = { version = "0.3.0-alpha.18", optional = true, package = "futures-preview", features = ["compat"] }

[dev-dependencies]
juniper = { version = "0.13.1", path = "../juniper", features = ["expose-test-schema", "serde_json"] }
env_logger = "0.5.11"
log = "0.4.3"
percent-encoding = "1.0"
