[package]
name = "juniper_warp"
version = "0.6.0"
edition = "2018"
authors = ["Tom Houl√© <tom@tomhoule.com>"]
description = "Juniper GraphQL integration with Warp"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper_warp"
repository = "https://github.com/graphql-rust/juniper"

[features]
subscriptions = ["juniper_graphql_ws"]

[dependencies]
anyhow = "1.0"
bytes = "1.0"
futures = "0.3.1"
juniper = { version = "0.15.1", path = "../juniper", default-features = false }
juniper_graphql_ws = { version = "0.2.1", path = "../juniper_graphql_ws", optional = true }
serde = { version = "1.0.75", features = ["derive"] }
serde_json = "1.0.24"
thiserror = "1.0"
tokio = { version = "0.2", features = ["blocking", "rt-core"] }
warp = "0.2"

[dev-dependencies]
env_logger = "0.8"
juniper = { version = "0.15.1", path = "../juniper", features = ["expose-test-schema"] }
log = "0.4"
percent-encoding = "2.1"
tokio = { version = "0.2", features = ["blocking", "macros", "rt-core"] }
url = "2"
