[package]
name = "juniper_warp"
version = "0.5.2"
authors = ["Tom Houl√© <tom@tomhoule.com>"]
description = "Juniper GraphQL integration with Warp"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper_warp"
repository = "https://github.com/graphql-rust/juniper"
edition = "2018"

[features]
subscriptions = ["juniper_subscriptions"]

[dependencies]
bytes = "0.5"
anyhow = "1.0"
thiserror = "1.0"
futures = "0.3.1"
juniper = { version = "0.14.2", path = "../juniper", default-features = false  }
juniper_subscriptions = { path = "../juniper_subscriptions", optional = true }
serde = { version = "1.0.75", features = ["derive"] }
serde_json = "1.0.24"
tokio = { version = "0.2", features = ["blocking", "rt-core"] }
warp = "0.2"

[dev-dependencies]
env_logger = "0.7.1"
juniper = { version = "0.14.2", path = "../juniper", features = ["expose-test-schema", "serde_json"] }
log = "0.4.3"
percent-encoding = "2.1"
tokio = { version = "0.2", features = ["blocking", "macros", "rt-core"] }
