[package]
name = "actix_subscriptions"
version = "0.1.0"
authors = ["Mihai Dinculescu <mihai.dinculescu@outlook.com>"]
edition = "2018"
publish = false

[dependencies]
actix-web = "3.0.0"
actix-cors = "0.4.0"

futures = "0.3.5"
tokio = { version = "0.2", features = ["rt-core", "macros"] }
env_logger = "0.7.1"
serde = "1.0.115"
serde_json = "1.0.57"
rand = "0.7.3"

juniper = { path = "../../juniper", features = ["expose-test-schema"] }
juniper_actix = { path = "../../juniper_actix", features = ["subscriptions"] }
juniper_graphql_ws = { path = "../../juniper_graphql_ws" }
