[package]
name = "actix_subscriptions"
version = "0.1.0"
edition = "2018"
authors = ["Mihai Dinculescu <mihai.dinculescu@outlook.com>"]
publish = false

[dependencies]
actix-web = "3.3"
actix-cors = "0.5"
futures = "0.3"
tokio = { version = "1.1", features = ["macros", "rt-core"] }
env_logger = "0.8"
serde = "1.0"
serde_json = "1.0"
rand = "0.7"

juniper = { path = "../../juniper", features = ["expose-test-schema"] }
juniper_actix = { path = "../../juniper_actix", features = ["subscriptions"] }
juniper_graphql_ws = { path = "../../juniper_graphql_ws" }
