[package]
name = "juniper_graphql_ws"
version = "0.2.3"
edition = "2018"
authors = ["Christopher Brown <ccbrown112@gmail.com>"]
license = "BSD-2-Clause"
description = "GraphQL over WebSocket protocol implementation for Juniper"
documentation = "https://docs.rs/juniper_graphql_ws"
repository = "https://github.com/graphql-rust/juniper"
keywords = ["apollo", "graphql", "graphql-ws", "juniper"]

[dependencies]
juniper = { version = "0.15.3", path = "../juniper", default-features = false }
juniper_subscriptions = { version = "0.15.3", path = "../juniper_subscriptions" }
serde = { version = "1.0.8", features = ["derive"], default-features = false }
tokio = { version = "1.0.2", features = ["macros", "rt", "time"], default-features = false }

[dev-dependencies]
serde_json = "1.0"
