[book]
title = "Juniper Book"
description = "User guide for Juniper (GraphQL server library for Rust)."
language = "en"
authors = [
    "Kai Ren (@tyranron)",
]
src = "src"

[build]
build-dir = "_rendered"
create-missing = false

[output.html]
git_repository_url = "https://github.com/graphql-rust/juniper"

[rust]
edition = "2024"
