[package]
name = "juniper_subscriptions"
version = "0.14.2"
authors = ["nWacky <gosha.evtushenko@gmail.com>"]
description = "Juniper SubscriptionCoordinator and SubscriptionConnection implementations"
license = "BSD-2-Clause"
documentation = "https://docs.rs/juniper_subscriptions"
repository = "https://github.com/graphql-rust/juniper"
edition = "2018"


[dependencies]
futures = { version = "=0.3.5", features = ["compat"] }
juniper = { version = "0.14.2", path = "../juniper", default-features = false }

[dev-dependencies]
serde_json = "1.0"
tokio = { version = "0.2", features = ["rt-core", "macros"] }
